# Generated by Django 5.1.3 on 2024-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, help_text='If more than one call number, then split them with comma(,)', max_length=255, null=True)),
                ('whatsap_number', models.CharField(blank=True, help_text='If more than one call number, then split them with comma(,)', max_length=255, null=True)),
                ('map_address', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
